### ISSUE TITLE
貌似最新版的微信这个插件已经失灵

### ISSUE THREAD

**Issue by realcarlos** [leftstick/jquery-wechat#2]
我查了一下，可能是微信取消了WeixinJSBridgeReady

**Comment by leftstick** [comment]
我在文档里已经做了标注，如下：
![snip20151215_1](https://cloud.githubusercontent.com/assets/1059956/11806933/40a7b284-a351-11e5-9b39-2d78e857b581.png)

如果需要微信开发，请直接使用官方提供的SDK。这个插件是在官方SDK出来之前提供大家开发用的，现在已经没必要了
